Fix toml-test scripts
Update tests/decoding_test.py to use the format used by the current
version of toml-test. I also removed Python 2 support (my distro doesn't
ship it, so I can't test it).

Also add tests/encoding_test.py for encoder tests

Still quite a few failures, mostly because it looks like it hasn't been
updated to use 1.0 yet:

    % toml-test ./decoding_test.py | tail -n2
      valid tests: 139 passed, 18 failed
    invalid tests: 230 passed, 53 failed

    % toml-test ./encoding_test.py -encoder | tail -n1
    encoder tests: 146 passed, 11 failed

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -22,20 +22,20 @@ jobs:
         with:
           go-version: 1.21
 
-      - name: get toml-test
+      - name: install toml-test
         run: |
-            git clone https://github.com/BurntSushi/toml-test
-          # cd toml-test/cmd/toml-test
-          # go build
+            go install github.com/toml-lang/toml-test/cmd/toml-test@v1.4.0
 
       - name: Run python tests
         run: |
             pip -q install "tox>=4"
             tox run-parallel --parallel-no-spinner
 
-      # TODO(warchant): this cmd is old, need to update it
+      # TODO(warchant): many tests fail
       # - name: Run go tests
       #   run: |
-      #       pip -q install setuptools
-      #       python setup.py install
-      #       ./toml-test/cmd/toml-test/toml-test -i ./tests -g ./tests/gotests.sh
+      #       export PYTHONPATH=.
+      #       e=0
+      #       toml-test          ./tests/decoding_test.py || e=1
+      #       toml-test -encoder ./tests/encoding_test.py || e=1
+      #       exit $e
